spring.application.name=gestion-biblioteca

# Puerto
server.port=${PORT:8080}

# ============================================================
# BASE DE DATOS
# ============================================================
# En local usa H2.
# En la nube, si existe DB_URL, utiliza PostgreSQL.

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/biblioteca;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ============================================================
# H2
# ============================================================
# Se puede usar localmente.
# En producción podemos desactivarla desde las variables
# de entorno.

spring.h2.console.enabled=${H2_CONSOLE:true}
spring.h2.console.path=/h2-console

# ============================================================
# JWT
# ============================================================
# La clave real se configurará como variable de entorno
# en el servidor.

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}